#!/usr/bin/env python3

import os.path

from aws_cdk import (
    aws_secretsmanager as secretsmanager,
    SecretValue as SecretValue,
    aws_iam as iam,
)
from cdk_nag import NagSuppressions
from constructs import Construct

dirname = os.path.dirname(__file__)


class IamUser(Construct):

    def __init__(self, scope: Construct, construct_id: str, params=None):
        super().__init__(scope, construct_id)

        # IAM user for Wickr IO bot. Required as Wickr IO doesn't make use of
        # EC2 instance role.

        self.wickrio_user = iam.User(
            self, 'user',
            user_name='wickr-io-user',
        )
        self.wickrio_user_secret = secretsmanager.Secret(
            self, 'user secret',
            secret_name='WickrIO-IAM-User-Secret',
            secret_object_value={
                'iam_user_name': SecretValue.unsafe_plain_text(self.wickrio_user.user_name)
            },
        )
        self.wickrio_user_secret.grant_read(params.wickrio_instance.ec2_instance_role)
        params.wickrio_code.integration_code.bucket.grant_read(self.wickrio_user)
        params.wickrio_config.wickrio_config.grant_read(self.wickrio_user)

        # ----------------------------------------------------------------
        #       cdk_nag suppressions
        # ----------------------------------------------------------------

        NagSuppressions.add_resource_suppressions(
            construct=self.wickrio_user,
            suppressions=[
                {
                    'id': 'AwsSolutions-IAM5',
                    'reason': 'Default read and write permissions generated by using CDK function grant_read().',
                    'appliesTo': [
                        'Action::s3:GetBucket*',
                        'Action::s3:GetObject*',
                        'Action::s3:List*',
                        f'Resource::arn:aws:s3:::{params.wickrio_code.integration_code.bucket.bucket_name}/*',
                    ]
                },
            ],
            apply_to_children=True,
        )
